const express = require('express');
const axios = require('axios');
const { Octokit } = require('@octokit/rest');
const netlify = require('netlify');
const OpenAI = require('openai');
require('dotenv').config();

const app = express();
const port = 3000;

app.use(express.json());
app.use(express.static('public'));

// OpenAI API
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// GitHub API
const octokit = new Octokit({
  auth: process.env.GITHUB_API_KEY,
});

// Netlify API (using basic deployment)
const netlifyClient = new netlify.Client({
  accessToken: process.env.NETLIFY_ACCESS_TOKEN,
});

app.post('/api/generateSoftware', async (req, res) => {
  const { projectName, projectDescription } = req.body;

  try {
    // Step 1: Use OpenAI to generate code based on description
    const aiResponse = await openai.completions.create({
      model: "text-davinci-003",
      prompt: `Create a simple project for: ${projectDescription}`,
      max_tokens: 500,
    });

    const generatedCode = aiResponse.choices[0].text;

    // Step 2: Create a GitHub repository and push the code
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: projectName,
      description: `Generated by AI: ${projectName}`,
      private: false,
    });

    await octokit.repos.createOrUpdateFileContents({
      owner: 'your-github-username',
      repo: repo.name,
      path: 'index.html',
      message: 'Initial commit with AI generated code',
      content: Buffer.from(generatedCode).toString('base64'),
    });

    // Step 3: Deploy to Netlify
    const deploy = await netlifyClient.deploy.create({
      site_id: 'your-site-id',
      draft: generatedCode,
    });

    // Send back the live URL
    res.json({
      status: 'success',
      url: `https://your-site-id.netlify.app`,
    });
  } catch (error) {
    console.error(error);
    res.json({ status: 'error', message: 'Something went wrong!' });
  }
});

app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}`);
});
